version: '2'
services:

  build:
    image: "klakegg/hugo:0.15"
    volumes:
     - .:/srv/src
     - ./target:/srv/target
    ports:
     - "1313:1313"

  server:
    command: server -w --bind 0.0.0.0
    image: "klakegg/hugo:0.15"
    volumes:
     - .:/srv/src
    ports:
     - "1313:1313"
